### ISSUE TITLE
Banner ItemStack name

### ISSUE THREAD

**Issue by Darthmineboy** [MilkBowl/VaultAPI#10]
Hey,

Seems that when I have an ItemStack of the banneritem and I try to get the name of it, it errors. 

Code:
    public String getItemname(ItemStack auctionitem){
        String s = null;
        Bukkit.broadcastMessage("0");
        Bukkit.broadcastMessage(Items.itemByStack(auctionitem).getName());

Seems to only be messaging the 0, and stops afterwards. Other items do work, so I think the list is just missing the item banner. 

Thanks in advance,

Darthmineboy

**Comment by Sleaker** [comment]
Banner items aren't supported through the API because of how many combinations are allowed via the sub-ids.

**Comment by Darthmineboy** [comment]
It always returns a value. Anyway, would perhaps be nice to just name it Banner then, regardless of the combination.

	public String getItemname(ItemStack auctionitem){
		String s = null;
		if(auctionitem.getType() == Material.BANNER){
			s = "Banner";
		}else if(Items.itemByStack(auctionitem).getName() == null){
			s = auctionitem.getClass().getName();
		}else{
			s = Items.itemByStack(auctionitem).getName();
		}
		if(auctionitem.getType().getMaxDurability() != 0){
			if(auctionitem.getDurability() != 0){
				s = "Damaged " + s;
			}
		}
		if(auctionitem.getItemMeta().hasEnchants()){
			s = "Enchanted " + s;
		}
		if(s.equals("Human Head")){
			SkullMeta skull = (SkullMeta) auctionitem.getItemMeta();
			if(skull.getOwner() != null){
				s = skull.getOwner() + "'s Head";
			}
		}else if(s.equals("Enchanted Book")){
			EnchantmentStorageMeta book = (EnchantmentStorageMeta) auctionitem.getItemMeta();
			String enchants = "";
			for(Enchantment enchant : book.getStoredEnchants().keySet()){
				String roman = "";
				if(book.getStoredEnchantLevel(enchant) == 1){
					roman = "I";
				}else if(book.getStoredEnchantLevel(enchant) == 2){
					roman = "II";
				}else if(book.getStoredEnchantLevel(enchant) == 3){
					roman = "III";
				}else if(book.getStoredEnchantLevel(enchant) == 4){
					roman = "IV";
				}else if(book.getStoredEnchantLevel(enchant) == 5){
					roman = "V";
				}
				enchants = WordUtils.capitalize(enchant.getName().toLowerCase()) + " " + roman + " " + enchants;
			}
			s = enchants + s;
		}
		s = auctionitem.getAmount() + "x" + s;
		return s;
		//return s;
	}

**Comment by Sleaker** [comment]
@Darthmineboy - it is named Banner regardless. If you use itemByStack it tries to lookup based on subid.  This is going to return null since there's no mapping for the banners with subids. You should be using Items.itemByType for Banners.

**Comment by Darthmineboy** [comment]
I've already added a check to see if the material is a banner, no need to use Vault for that :P.

Anyway, thanks for the support.

**Comment by Sleaker** [comment]
@Darthmineboy - right, I'm not sure if you were integrating ItemInfo's into your project. I'll look at getting this in so for any banner item it just returns back the ItemInfo for the Banner type instead.
