### ISSUE TITLE
Player Prefixes

### ISSUE THREAD

**Issue by hkerby** [MilkBowl/VaultAPI#104]
I'm not sure if this is a vault issue, but when players join my server, their prefixes are %vault_prefix%, and suffixes are %vault_suffix%. I have no idea how to clear them or change them. I am currently using EssentialsX, EssenstialsXchat, LuckPerms, NameTagEdit, and Vault.

**Comment by Sleaker** [comment]
This isn't an issue with vault, it's in a plugin's configuration, most likely Xchat.
