### ISSUE TITLE
Land Protection API

### ISSUE THREAD

**Issue by RoinujNosde** [MilkBowl/VaultAPI#107]
How about an API for land protection plugins? (WorldGuard, GriefPrevention, etc)

They could register a Protection implementation that would contain methods such as:
Land getAt(Location loc);
boolean isOwner(Player p, Location loc);
boolean canBuild(Player p, Location loc);

Land could be an interface with general methods:
Block getMinPoint();
Block getMaxPoint();
List<UUID> getOwners() or List<String> (in case groups are supported as owners)

**Comment by Sleaker** [comment]
Vault is not looking to add additional APIs like this it was looked into at one point, but seemed likely that there weren't enough differing plugins like this that an individual plugin could handle linking with the ones it wanted. Also I believe worldguard already has an API for interop, but in a similar vein, other plugins would need to utilize it's registration.
