### ISSUE TITLE
Getting caller of function

### ISSUE THREAD

**Issue by KoenvdStroom** [MilkBowl/VaultAPI#113]
Hello there,

I was wondering if it is possible to get the plugin which is calling a function. 
For example,
Plugin A is calling Vault function withdraw on a player, is there a way for the economyplugin to know that Plugin A called the withdraw function?

**Comment by Geolykt** [comment]
Not really possible without analyzing the stacktrace.
You can make use of https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Thread.html#getStackTrace(), however I strongly discourage using it given that it isn't the most performant thing in the world.

Allowing for this behaviour would require an API rewrite at best

**Comment by KoenvdStroom** [comment]
Aight thanks
