### ISSUE TITLE
PlaceholderAPI no longer working.

### ISSUE THREAD

**Issue by LuluxClient** [MilkBowl/VaultAPI#115]
Hello, I'm trying to setup a leaderboard and the placeholder %vault_eco_top_player_#% is just sending a blank message (tried %vault_eco_top_player_1% and %vault_eco_top_player_PlayerName%) and I saw multiple people were having this issue.

**Comment by Geolykt** [comment]
This is NOT an issue with the vault API in specific, please inform the responsible expansion of this
