### ISSUE TITLE
Service provider return null

### ISSUE THREAD

**Issue by Galajus** [MilkBowl/VaultAPI#118]
`RegisteredServiceProvider<Economy> rsp = getServer().getServicesManager().getRegistration(Economy.class);`

I'm using guide from readme, in 1.16 work but not in 1.17, java 16 (server and project)

Is other way to implement economy or i must wait to vault update? :c

**Comment by Geolykt** [comment]
If it returns null it means there is no economy registered (always get that value lazily!) - fixing it at the vault side is not really possible.
On the plugin side of things you may want to register a dummy economy instead but it is often unlikely that it is needed

**Comment by Galajus** [comment]
Thank you, that was problem with my plugin. 🤦
