### ISSUE TITLE
Remove deprecated methods from the Economy interface

### ISSUE THREAD

**Issue by lokka30** [MilkBowl/VaultAPI#121]
Methods such as [this](https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/economy/Economy.java#L86) have been deprecated for quite a while now. More than adequate time has been provided for plugins to use OfflinePlayer methods instead.

**Comment by Geolykt** [comment]
What would the replacement be for non-player accounts? This would basically brick 98% of such plugins

**Comment by lokka30** [comment]
> 
> 
> What would the replacement be for non-player accounts? This would basically brick 98% of such plugins

I was under the assumption these methods were purely for player account activity only, where the name variable was meant to be a player's username.

**Comment by Geolykt** [comment]
In theory that's the case, but most plugins don't adhere to that logic. The Bank API isn't a suitable replacement so I don't blame them.

**Comment by lokka30** [comment]
> 
> 
> In theory that's the case, but most plugins don't adhere to that logic. The Bank API isn't a suitable replacement so I don't blame them.

If an API is being used incorrectly I believe it does not mean that the maintainers should allow it :) I know Towny is or used to misuse these methods and it caused annoyances for myself when I was developing my old economy plugin. Perhaps Vault can offer non-player balance alternatives? I agree that the Bank API is an unsuitable replacement.

**Comment by lokka30** [comment]
I believe it would be much better if Vault had separate non-player-transaction methods, and removed these deprecated methods. 
Then, economy plugins can deal with Vault methods in a way that doesn't have to band-aid their code because a few plugins decide to misuse it (even though they are perfectly capable of having their own databases).

On a side question, @Geolykt, what ways do you think the Bank API can be improved to become suitable for these types of applications?

**Comment by lokka30** [comment]
This will be fixed with #112.
