### ISSUE TITLE
Plugin no nametag and Vault

### ISSUE THREAD

**Issue by Frithy0** [MilkBowl/VaultAPI#123]
Hi ! I have a problem, i use vault with a other plugin for hide the nametag. 
This plugin works but when i add vault on my server, it don't works....
Can you help me at to understand, please ?

**Comment by lokka30** [comment]
It must be a coincidence. Vault does not do anything with player nametags, I'm certain I can safely assume that

**Comment by Frithy0** [comment]
Hmm ok, if you say so, but i have test with several plugin of "no nametag"

**Comment by Geolykt** [comment]
> It must be a coincidence. Vault does not do anything with player nametags, I'm certain I can safely assume that

This is not fully right. Plugins could integrate into Vault and thus produce different behaviour than without Vault. Especially the permissions side of things is worth to note.
That being said, yes, it is unlikely to be a Vault issue but rather something wrong with the plugin responsible for disabling the nametags. Perhaps there is a permission issue in your configuration?

**Comment by Frithy0** [comment]
Hmm ok, so sorry, i go check that =) 
Thank's
