### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Jcodeerd** [MilkBowl/VaultAPI#125]
Hi,
Is there any way to log the transactions?

**Comment by Geolykt** [comment]
As of now, no

**Comment by Jcodeerd** [comment]
Are there any plans on adding it?

**Comment by Geolykt** [comment]
It's a bit hard to implement at vault level without rewriting it in a larger capacity to be honest.
I cannot say for sure if there are plans on adding anything, but looking at the repo activity I deem it to be unlikely

**Comment by Jcodeerd** [comment]
Sad, do you know any other plugins that can log economy?

**Comment by lokka30** [comment]
Ask your economy plugin to add the functionality in :)

**Comment by Jcodeerd** [comment]
Okido, ill try that later. Thanks :)
