### ISSUE TITLE
Ban API

### ISSUE THREAD

**Issue by Leonardo-DGS** [MilkBowl/VaultAPI#131]
It would be useful a Ban API, for example to detect if a player is banned, or to ban a player not only with the vanilla ban system.

The Bukkit API gives you the possibility to check if a player is banned, to ban a player etc, but it's only for the Vanilla bans, this API would make possible those methods even for custom ban plugins (that store bans in a different location).

**Comment by Geolykt** [comment]
You really like your Ban API, don't you?

**Comment by Leonardo-DGS** [comment]
If you want, I can make a pull request.
