### ISSUE TITLE
ı cant %vault_eco_balance_formatted%  and give error

### ISSUE THREAD

**Issue by budur01** [MilkBowl/VaultAPI#136]
https://prnt.sc/6FRAe0cp3ghc
https://prnt.sc/Pi5TjhQ7dS2h
https://prnt.sc/v9jSCzbn7UNX
and give error another plugin https://prnt.sc/v9jSCzbn7UNX
help me

**Comment by Geolykt** [comment]
There is no error from what I can see.

Not a vault API issue, please refer to the correct repositories (or look at one of the other two-hundred open issues that describe the exact issue).

If I had faith in humanity, I'm sure that I have lost it by now

**Comment by budur01** [comment]
> There is no error from what I can see.
> 
> Not a vault API issue, please refer to the correct repositories (or look at one of the other two-hundred open issues that describe the exact issue).
> 
> If I had faith in humanity, I'm sure that I have lost it by now

ı cant use %vault_eco_balance_formatted%, expression is installed , essentials is installad, placeholderapi is installed

**Comment by budur01** [comment]
but okey problem is vault, not vault api

**Comment by Geolykt** [comment]
The problem is neither. Vault does not and likely will not provide placeholders. Report the issue to https://github.com/PlaceholderAPI/Vault-Expansion/issues instead.
