### ISSUE TITLE
I can't make plugin with vault.

### ISSUE THREAD

**Issue by Dotmazy** [MilkBowl/VaultAPI#142]
I try to copy all the example code.
`private boolean setupEconomy() {
        if (getServer().getPluginManager().getPlugin("Vault") == null) {
            return false;
        }
        RegisteredServiceProvider<Economy> rsp = getServer().getServicesManager().getRegistration(Economy.class);
        if (rsp == null) {
            return false;
        }
        econ = rsp.getProvider();
        return econ != null;
    }`
getServer().getPluginManager().getPlugin("Vault")  return true but
rsp return null.

**Comment by Geolykt** [comment]
Do you have an economy plugin installed? If not, then either you need to install one on the server or code it yourself

**Comment by cerealcable** [comment]
Closing this issue as no response from the issue creator. If you want further support please respond in a timely manner.
