### ISSUE TITLE
Not all brewable potions IDs have valid ItemInfo

### ISSUE THREAD

**Issue by RypoFalem** [MilkBowl/VaultAPI#15]
I discovered this when a Vault API call ( Items.itemByStack(ItemStack itemStack) ) was failing to recognise some splash potions of slowness but not others.

The issue is that sometimes potions with the exact same effect can have different IDs. This includes both brewable and non-brewable potions.

This information taken from the [minecraft wiki](http://minecraft.gamepedia.com/Potion#Item_data) helps explain the issue:

> Bits 13 and 14 (8192 and 16384) determines whether the potion is a drinkable potion or a splash potion. If bit 13 is true, it's drinkable. If 14 is true, it's a splash potion.
> Bits 7-12 and 15 are ignored, so many potions with distinct data values will have the same properties.

Any potion that has bits 7-12 or bit 15 of the potion's damage value set as 1 will not be recognised by the api (I am not sure if this is possible to brew) . In addition, it seems that when brewing any splash potion, the potion will only have the ID that you recognise if the gunpowder was added last. If any other ingredient (usually a fermented spider eye) is added after the gunpowder then both bits 13 and 14 will be set to true. Since the API's hardcoded values assume that bit 13 is false for splash potions (and it isn't always true with vanilla mechanics), the API fails to recognise some valid potions.

An example: 
water bottle + netherwart + sugar + fermented spider eye +  gunpowder yields a Splash Potion of Slowness (potion:16394)

However

water bottle + netherwart + sugar + gunpowder + fermented spider eye yields a functionally identical Splash Potion of Slowness but with a different damage value (potion:24586)

I can kind of understand why non-brewable (but obtainable via commands) items like potion of saturation aren't on your list. However, it seems that if potion's ItemInfo was generated by reading the data value to determine the potion type rather than hardcoding the data value for every possible potion type, you could support all brewable potions and as side effect also support non-brewable ones.

**Comment by Sleaker** [comment]
This is why the item API hasn't been updated since it was initially done. meta data mucks it up a ton and it would need a re-write to support everything 'correctly'

**Comment by Sleaker** [comment]
ItemAPI has been removed, I don't think it will be coming back anytime soon as the client UI now takes care of most of the things that the API was being used for.
