### ISSUE TITLE
Cannot hook Vault's economy

### ISSUE THREAD

**Issue by FeozRu** [MilkBowl/VaultAPI#159]
Can anyone give me a suggestion, where is trouble?
net.milkbowl.vault.economy.Economy is not presented in Bukkit.getServicesManager()
List of Bukkit.getServicesManager().getKnownServices():
```
net.milkbowl.vault.metrics.bukkit.Metrics
net.milkbowl.vault.chat.Chat
de.tr7zw.nbtapi.utils.ApiMetricsLite
com.alonsoaliaga.alonsolevels.metrics.Metrics
javax.script.ScriptEngineManager
net.luckperms.api.LuckPerms
net.milkbowl.vault.permission.Permission
```

Server core (paper) version: git-Paper-519 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 936205b)
Plugins list:
 AlonsoLevels, ArmorStandTools, HuskSync, JSEngine, LuckPerms, LuckpermsCommandExecute (my plugin), momojs, NBTAPI, PlasmoVoice, Vault
Vault version 1.7.3-b131

**Comment by Geolykt** [comment]
Yet another wontfix "issue": Vault does not provide an economy by default. You need to have a plugin that provides an economy, which you do not have. Hence no service that provides an economy and thus you have your issues.

**Comment by FeozRu** [comment]
Got it. Thanks
