### ISSUE TITLE
VaultAPI not removing permissions.

### ISSUE THREAD

**Issue by KubqoA** [MilkBowl/VaultAPI#16]
Hello, I am developing plugin in which part is function which removes or adds permissions based on gamemode switching. The problem is with removing, because permissions which were set before for example in PermissionsEx are not being removed. Code which I use:
`
public static void removePermission(Player player, String permissionnode) {
        permission.playerRemove(player,permissionnode);
}`

Of course I have previously initialized the VaultAPI using the setup etc.

**Comment by Sleaker** [comment]
Hi, thanks for filing a bug report, unfortunately you did it against the wrong project. All of the implementation details for the Permission systems are found in Milkbowl/Vault. One thing to be aware of is that playerRemove the way you're calling it only removes world specific permissions for the player. Please remember to check the documentation for the operation you are performing: https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/permission/Permission.java#L345

If you need to remove a global permission you will need to use the other method with a null world.
