### ISSUE TITLE
Java 8 problem with Vault as dependency

### ISSUE THREAD

**Issue by hanakocz** [MilkBowl/VaultAPI#22]
Hi, we were making one plugin which would take forge mod (items + accounts) and connect them to the Vault Economy system, which is working,but only in Java 7, not in Java 8. With Java 8 there are unresolved compilation errors with Vault. 
Can you look, if you won't get any idea WHY or WHAT can do it? 

Java 7:
 - Plugin loads, and other plugins can use its economy thingies via Vault (used latest Vault and it worked well)

Java 8:
Same error with Vault 1.4.1 and Vault 1.5.6 (we use Minecraft 1.7.10 for this, so that's why we tried 1.4 version of Vault, but then other plugins do not work with Economy support via Vault)
http://pastebin.com/2QYNh7TP

We used to compile the plugin with Java 8 in all scenarios, and everytime succesfully, it only refuses to work on server with Java 8.

Is there anything that would break Vault usage on Java 8? Because other things (and vault itself) is running regardless if Java 7 or 8 ....

Thanks for any help or hint.

**Comment by Sleaker** [comment]
Sounds like you're not setting up classpaths properly for compiling. I have no issues compiling between different versions of java.
