### ISSUE TITLE
1.11 support

### ISSUE THREAD

**Issue by Botanistt** [MilkBowl/VaultAPI#29]
Hello.
Would be nice if you updated this plugin to 1.11.
Thanks.

**Comment by falukerites** [comment]
+1

**Comment by stuntguy3000** [comment]
It is certainly compatible with the latest versions of MC.

**Comment by Botanistt** [comment]
why is vault deleted from bukkit?

**Comment by stuntguy3000** [comment]
https://dev.bukkit.org/projects/vault

**Comment by Sleaker** [comment]
also: https://mods.curse.com/bukkit-plugins/minecraft/vault
