### ISSUE TITLE
Why are there no methods to create and remove groups?

### ISSUE THREAD

**Issue by AndrewSumsion** [MilkBowl/VaultAPI#33]
I'm sorry if this is in the wrong place to post this, I didn't know where else.
I would really appreciate if someone could add this, or explain why it's not possible.
Thanks!

**Comment by no372** [comment]
The answer for question is _(in my opinion)_ is that the various plugins use **different ways** to create or remove a group. Also, it is possible that the method which handles the group creation _(or removal)_ is **private** or **package private** which means you **can not access** it from any other class **directly**.

**Comment by AndrewSumsion** [comment]
Isn't that what Vault is all about though? Combining all of the plugins' ways of doing it into one method?
Also there are workarounds to accessing private methods...

**Comment by no372** [comment]
Yes, they trying to _connect_ the most _popular_ plugins with a bridge, so when you develop your plugin, you only have to write a method **one way**, with only **one dependency**, and it'll be compatible with _various plugins_. I _personally_ think the group management should be the plugins' _private business_.
Also there are some plugins that only **read** the groups from a **configuration file**, and at runtime you _can not_ **manage** them.
_It's just my way of thinking_, maybe it's not this way.

**Comment by Sleaker** [comment]
Different plugins handle groups (or not at all) differently. Some of them don't provide APIs for it, and there's no universal way for this to be handled. It's also edge-functionality that if you're trying to develop a plugin that does these types of operations, it would need to be done in such a specific way for each Permission system you wanted to support that you should be connecting and dealing with the plugins directly to begin with.  Vault is an adapter for the majority of use-cases. If your use case is not supported in vault then it's most likely something that is too specific for inclusion, or not worth the maintenance upkeep within Vault.
