### ISSUE TITLE
Any item with max durability of 0 returns null

### ISSUE THREAD

**Issue by FlyingPikachu** [MilkBowl/VaultAPI#36]
For example. IRON_ORE.  It doesn't have any variants (unlike Dirt, with Coarse Dirt and Podzol). As such the current code returns null for Iron Ore; it does not pass .isDurable()

https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/item/Items.java#L820

**Comment by Sleaker** [comment]
ItemBystack is broken vs itemByType?

**Comment by FlyingPikachu** [comment]
@Sleaker Correct.

**Comment by FlyingPikachu** [comment]
Wow forgot I opened this! Finding itemByStack() is still broken when checking a STONE_BUTTON just now, which has a max durability of 0. Once can circumvent this by using itemByType() instead, but I'd like to propose a fix.
