### ISSUE TITLE
Add UUID support

### ISSUE THREAD

**Issue by Phoenix616** [MilkBowl/VaultAPI#37]
Currently methods only take in the player's name or an OfflinePlayer object. They should also support direct player UUIDs so that the plugin itself can decide what to do with it. This is important as getting an OfflinePlayer might be more time consuming than passing in the UUID (or even the player's name which shouldn't be deprecated in the first place) as the plugin itself probably already maps names/uuids.

**Comment by Sleaker** [comment]
This is a requirement to make APIs sane. Note: vault doesn't actually process data itself, so it provides an interface that's most sane for others to utilize. UUIDs weren't around for the popular permission/economy systems in use so it wasn't the standard.

**Comment by Phoenix616** [comment]
> UUIDs weren't around for the popular permission/economy systems in use so it wasn't the standard

This issue is about adding UUID support to the VaultAPI which all major plugins support nowadays.
