### ISSUE TITLE
Add UUID-playername storage/mapping API

### ISSUE THREAD

**Issue by Phoenix616** [MilkBowl/VaultAPI#38]
Currently most plugins (e.g. all economy, logging, permissions and ban plugins) keep their own mapping of playernames to UUIDs. The VaultAPI would be the perfect place to provide a unified interface to access this information from plugins that already provide that.

Additionally this could be expanded to also provide a player name history and last seen API (which should probably be separate from the sole lookup API as most plugins that store the UUID-name mapping will probably not store the other information too)

**Comment by Sleaker** [comment]
Sounds like a good idea for a different plugin.

**Comment by Phoenix616** [comment]
Why? Isn't the idea behind the VaultAPI to provide a unified interface to access the data of other plugins? (In this case playername to uuid mapping?)

**Comment by Sleaker** [comment]
No, Vault is intended to provide access to economy and permission functions only.

**Comment by Phoenix616** [comment]
Currently it only provides access to economy, permissions and chat (and some item stuff). I don't see the issue in adding another category?

Especially when the "[intend] to provide access to economy and permission functions **only**" isn't mentioned anywhere but the [Vault readme](https://github.com/MilkBowl/Vault#why-vault) rather states "an abstraction layer not only for Economic plugins but also Permission plugins as well. **The future will likely add more**, but what types" which hints at future categories, and this one should've been added long ago as now every single plugin that does something with players stores their own uuid->playername mappings which is quite absurd and wastes space.

**Comment by Sleaker** [comment]
If you need the feature then why don't you make it?

**Comment by Phoenix616** [comment]
I have no issues with writing this and submitting a PR if the chance of it getting accepted is there. Getting your issues closed without any discussion is kinda discouraging though...
