### ISSUE TITLE
How TF you get maven to work

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [MilkBowl/VaultAPI#44]
I am using maven to build my plugins and I want my core plugin to hook to my Nexus OSS. However I cannot find any guide and you clearly have it working. How did you achieve this???

**Comment by Sleaker** [comment]
Hey sorry @xXXIMMATTHEWXXx  - I'm not really able to go into how to setup and configure a self-hosted nexus server as I'm not the one that manages any of that, and I don't have the time to go into all of the setup pieces that got it working on the plugin side.  If you're having trouble in the authorization section that's handled with tokenized auth keys via travis-ci.
