### ISSUE TITLE
Why ignore intangible materials?

### ISSUE THREAD

**Issue by FlyingPikachu** [MilkBowl/VaultAPI#46]
In reference to: https://github.com/MilkBowl/VaultAPI/blob/master/src/test/java/net/milkbowl/vault/test/ItemTest.java#L19

Why does the API even bother ignoring these? This seems like unnecessary overhead and has created a problem for one of my users, https://github.com/FlyingPikachu/Quests/issues/282, which I will now describe:

A quest to break a few blocks of REDSTONE_ORE is made. However, hitting REDSTONE_ORE turns it into GLOWING_REDSTONE_ORE. When the ore finally breaks, the GLOWING_REDSTONE_ORE is ignored and results in a NullPointerException via itemByType()

**Comment by Sleaker** [comment]
You've found the unit tests.. not the actual run-time code.

**Comment by FlyingPikachu** [comment]
Think I need my head checked, thanks.
