### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by SirYwell** [MilkBowl/VaultAPI#48]
It seems like Vault can't be used as dependency at the moment, because http://nexus.hc.to/ reponds with a 502. Is this a temporary problem?

**Comment by TheE** [comment]
Same problem here.

Maybe the Vault team should just consider using a hosted solution like [JitPack](https://jitpack.io) or [Bintray](https://bintray.com)...

**Comment by zPirroZ3007** [comment]
Same problem for me. Any resolution?

**Comment by eUipKh** [comment]
**NetBeans:**

> pom.xml
https://prnt.sc/iewqol
Download Vault and _'Mannualy install artifact'_
https://prnt.sc/iewpsz

**Comment by games647** [comment]
Or just use JitPack directly. It already works without any modifications:

```xml
	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
```

```xml
	<dependency>
	    <groupId>com.github.MilkBowl</groupId>
	    <artifactId>VaultAPI</artifactId>
	    <version>8dc0859cba</version>
	</dependency>
```

**Comment by Sleaker** [comment]
Currently being looked at.

**Comment by Sleaker** [comment]
Fixed
