### ISSUE TITLE
Event System

### ISSUE THREAD

**Issue by mr2013** [MilkBowl/VaultAPI#5]
At first glance at the API, there does not appear to be a means to trigger an event when something happens via Vault, such as a permission change, or an economy balance transfer. Would it be possible for something like this to be added in? I've a plugin that displays a player's balance to them, via polling, and it would be a lot more efficient to only run calls on actual data changes.

**Comment by Sleaker** [comment]
This has been discussed at length. There will never be events in Vault.

**Comment by mr2013** [comment]
Can you point me to these discussions, which provide the rationale for this decision? Google has not returned anything that substantiates your claim. I would love to know the rationale behind refusing to implement a system which will reduce consumption of disk/db IO and CPU cycles, which are two big bottlenecks in bukkit performance.

**Comment by Sleaker** [comment]
https://github.com/MilkBowl/Vault/issues?q=is%3Aissue+is%3Aclosed+events

**Comment by mr2013** [comment]
I forgot to have the search focus on closed events, my bad. That explains quite well, apologies for my tartness and noise.
