### ISSUE TITLE
Checking if the server has Vault is useless.

### ISSUE THREAD

**Issue by Demeng7215** [MilkBowl/VaultAPI#50]
http://prntscr.com/ige1h0
Checking if the server has Vault does nothing, since if the server does not have Vault, the plugin will not enable and will just throw an exception:
http://prntscr.com/ige1t7
Dependencies are checked before onEnable() is called.

**Comment by Sleaker** [comment]
sure, so change the example code in your actual plugin? It wont detrimentally affect end users to have the check.

**Comment by Demeng7215** [comment]
Sorry, I meant to create a pull request and change it as it may be misleading for beginners who do not know about this.
