### ISSUE TITLE
Waring using double !

### ISSUE THREAD

**Issue by Zayceur** [MilkBowl/VaultAPI#51]
Hello,

I just tried to do a economy plugin based on the VaultAPI but I saw that the operations done on accounts are with doubles. That's not good !
For example (in Java) this code :
```
double d = 0;
d += 0.1;
d += 0.1;
d += 0.1;
d += 0.1;
d += 0.1;
d += 0.1;
d += 0.1;
d += 0.1;
d += 0.1;
d += 0.1;
System.out.println(d);
```

Shows : 0.9999999999999999
As we know, it should be 1.0 !

I don't think it's good in any economy plugin to lose some money just because of that.

To avoid those "loses" we need to change the interface _Economy_ to use BigDecimal instead of double. Here's the same example but with BigDecimal :
```
BigDecimal bg = BigDecimal.ZERO;
bg = bg.add(new BigDecimal("0.1"));
bg = bg.add(new BigDecimal("0.1"));
bg = bg.add(new BigDecimal("0.1"));
bg = bg.add(new BigDecimal("0.1"));
bg = bg.add(new BigDecimal("0.1"));
bg = bg.add(new BigDecimal("0.1"));
bg = bg.add(new BigDecimal("0.1"));
bg = bg.add(new BigDecimal("0.1"));
bg = bg.add(new BigDecimal("0.1"));
bg = bg.add(new BigDecimal("0.1"));
System.out.println(bg.toString());
```

And it shows : 1.0

I hope someone will change that.

Best regards, Zayceur

**Comment by Sleaker** [comment]
Vault used double because that's what all of the economies supported. I agree it's less than ideal and result in loss of precision in rare cases, but as an API that was built for compatibility it's not possible at this point to change.

**Comment by Zayceur** [comment]
> in rare cases

In fact, every number that can't be represented as a finite sum of power of 2 (there's a LOT of them). See https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency#answer-3730040.

There's another issue too, when adding a big number to a small one, the value of the bigger stay unchanged.

> but as an API that was built for compatibility it's not possible at this point to change.

Why not add new functions that use BigDecimal instead of double and add `@Deprecated` to the ones that use double, as it was done when using UUID instead of username ?
