### ISSUE TITLE
Recaptcha netbeans and maven

### ISSUE THREAD

**Issue by Sahariza** [MilkBowl/VaultAPI#61]
Looks like your maven repo is behind recaptcha "protection". So i (and others) can't reach it from IDE.
Can you please do something with it?

`Failed to read artifact descriptor for net.milkbowl.vault:VaultAPI:jar:1.6: Could not transfer artifact net.milkbowl.vault:VaultAPI:pom:1.6 from/to vault-repo (http://nexus.hc.to/content/repositories/pub_releases): Access denied to: http://nexus.hc.to/content/repositories/pub_releases/net/milkbowl/vault/VaultAPI/1.6/VaultAPI-1.6.pom , ReasonPhrase:Forbidden. -> [Help 1]`

**Comment by Sleaker** [comment]
This should no longer be an issue going forward, however if the webservice experiences ddos issues it will have to be re-enabled.
