### ISSUE TITLE
Documentation for createPlayerAccount(OfflinePlayer, String) is unclear

### ISSUE THREAD

**Issue by timmyrs** [MilkBowl/VaultAPI#64]
https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/economy/Economy.java#L351

The global balance probably isn't a boolean.

**Comment by Sleaker** [comment]
createPlayerAccount doesn't return a starting balance, it returns if the account creation was successful or not.

**Comment by Sleaker** [comment]
oh I see, just a documentation thing on line 351. thanks for the report.
