### ISSUE TITLE
Crashes Plot2

### ISSUE THREAD

**Issue by CrunchyChicken** [MilkBowl/VaultAPI#67]
i couldn't figure out what was breaking plot2 and the dev's insisted it wasn't them so i one by one added back every plugin having EssentialsX, Luck Perms, World Edit beta5, and Plot2 as the base doing a server start after each and watching if plot2 enabled. When i went and added vault (I NEED THIS) plot2 enabled but crashed and stopped working. It seems there's some compatibility issue.

Im using spigot1.13.2 the latest version of P2 and Vault

Thank you i appreciate you taking the time to read this and hope its fixed soon! <3

**Comment by Sleaker** [comment]
Vault doesn't do very much directly on the server, it just provides an API for plugins to communicate with each other in a standard way.  If your server becomes unstable when adding Vault then you have a plugin that has additional functionality being turned on when it sees Vault is available for use. It's not an issue in Vault itself.  I can't help point out where the problem might be without some kind of logs, and even then you're most likely posting the issue toward the wrong pluin. Sorry!

**Comment by CrunchyChicken** [comment]
im sorry, just frustrating when one dev blames the other then vice versa so im just s.o.l

**Comment by Sleaker** [comment]
@CrunchyChicken - I'm not blaming anyone here. I'm just pointing out that Vault is an interface layer, it's a passive plugin that just facilitates communication. The only thing it does if it's loaded on the system by itself is add a couple permissions for it's own use and perform a web request to get the latest version available, and send plugin version statistics to bstats.org - All other code in Vault is passive requests that get forwarded to other plugins, so the best place to start is with other plugins as Vault is just a thin layer to facilitate communication between them.

**Comment by CrunchyChicken** [comment]
Sorry I was saying that they’re saying it’s not them it’s you and to request from you so I’m kind of stuck between a rock and a hard place and not really knowing what to do to fix my problem because I deafinately need both plug-ins

**Comment by Sleaker** [comment]
@CrunchyChicken if you don't have server logs, you wont be able to get very far in the debug process :(
