### ISSUE TITLE
Vault repository down?

### ISSUE THREAD

**Issue by GeertBraakman** [MilkBowl/VaultAPI#68]
Hello i just wanted to ask if the vault repository is down.
[http://nexus.hc.to/content/repositories/pub_releases](http://nexus.hc.to/content/repositories/pub_releases)

![image](https://user-images.githubusercontent.com/36223190/52724691-1d125100-2fb0-11e9-9f9a-b76d110ce8d7.png)

**Comment by GeertBraakman** [comment]
![image](https://user-images.githubusercontent.com/36223190/52724774-4501b480-2fb0-11e9-9b90-ecd8f7eccf0f.png)

**Comment by KraftLegos** [comment]
Getting the same issue!

**Comment by DeepRobin** [comment]
yes, too. 
I cannot build my project :c

**Comment by DeepRobin** [comment]
@MilkBowl 
@Sleaker 
@mung3r 
@cerealcable 
Sorry, for mentioning your @-names but it is important. Vault is very good library and we all need the repository.

**Comment by OllieMartin** [comment]
Same issue here. Hopefully will be up again soon!

**Comment by Sleaker** [comment]
It's being looked in to.

**Comment by OllieMartin** [comment]
The issue appears to now be resolved!

**Comment by wysohn** [comment]
Hello, it seems to be down again. Any news? @Sleaker

**Comment by DeepRobin** [comment]
Yes it's down again

**Comment by DeepRobin** [comment]
@Sleaker Maybe it is the same issue
