### ISSUE TITLE
Repository offline

### ISSUE THREAD

**Issue by RodrigoCarvalho31** [MilkBowl/VaultAPI#69]
Repository http://nexus.hc.to/content/repositories/pub_releases is offline, please fix.

**Comment by Chasewhip8** [comment]
Can also confirm this is the case

**Comment by Haileykins** [comment]
Can also confirm, still

**Comment by Chasewhip8** [comment]
Just build it locally and it will be fine. Remove the repo and build local

**Comment by Heartz66** [comment]
Meanwhile, use system scope directing to your `Vault.jar`

**Comment by Sataniel98** [comment]
Yeah, but even if I remove the Vault repo, Maven still tries to access it because there are other dependencies that use this repo. The repo doesn't seem to be 404-down but somehow erroneous. It loads forever until I get a 504 gateway time-out error. That sucks because Maven tries to access it over and over again for each dependency.

**Comment by Skyost** [comment]
Same for me. @MilkBowl why not [self-hosting it using Github](https://stackoverflow.com/a/14013645/3608831) or using something like Jitpack ?

**Comment by md678685** [comment]
You can also swap the Vault repo for the [EssentialsX build server Maven repo](https://ci.ender.zone/), which also avoids having to change the build number to a commit hash:

### Gradle
```gradle
repositories {
    // ...
    maven { url 'https://ci.ender.zone/plugin/repository/everything/' }
}

dependencies {
    // ...
    compileOnly 'net.github.MilkBowl:VaultAPI:1.7'
}
```

### Maven
```xml
<repositories>
    <!-- ... -->
    <repository>
        <id>essx-repo</id>
        <url>https://ci.ender.zone/plugin/repository/everything/</url>
    </repository>
</repositories>

<dependencies>
    <!-- ... -->
    <dependency>
        <groupId>net.milkbowl.vault</groupId>
        <artifactId>VaultAPI</artifactId>
        <version>1.7</version>
        <scope>provided</scope>
    </dependency>
</dependencies>
```

**Comment by FlyingPikachu** [comment]
![batman-bat-signal-light_141264](https://user-images.githubusercontent.com/2267126/53310965-f4763b00-387c-11e9-95ee-dd297c6906a6.jpg)

**Comment by md678685** [comment]
Still appears to be returning a 502 for me, but now it's instant instead of waiting for a long time.

**Comment by Sleaker** [comment]
@md678685 I've tagged it onto jitpack to attempt to alleviate the hosting issues: 
https://jitpack.io/#MilkBowl/VaultAPI/1.7
