### ISSUE TITLE
Mark the commits of released versions with git tags

### ISSUE THREAD

**Issue by TheE** [MilkBowl/VaultAPI#70]
Could you mark the commits of each released API version with a [git tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) equal to that version, e.g. commit 5b8dc3a7063ccc330f16d3e9676b40b4662b00ee with the tag `v1.7`?

This would allow usage of tools such as [JitPack](https://jitpack.io/#MilkBowl/VaultAPI) to build against VaultAPI without having to build against a commit hash. You could even replace your currently offline repository (#69) with JitPack this way without having to setup and configure any infrastructure by yourself.

I would submit a PR, but unfortunately, git tags cannot be parts of PRs.

**Comment by Sleaker** [comment]
I'll look into using jitpack when I get a chance, thanks for the suggestion.

**Comment by Sleaker** [comment]
https://jitpack.io/#MilkBowl/VaultAPI/1.7

**Comment by TheE** [comment]
Awesome. 👍
