### ISSUE TITLE
Repo is down again

### ISSUE THREAD

**Issue by MythTheWolf** [MilkBowl/VaultAPI#71]
Same old bad gateway from nginx.

**Comment by TheE** [comment]
You can easily switch to [JitPack](https://jitpack.io/#MilkBowl/VaultAPI/1.7) without changing your version number, as the team added git tags:
````
<repositories>
	<repository>
	    <id>jitpack.io</id>
	    <url>https://jitpack.io</url>
	</repository>
</repositories>
<dependency>
    <groupId>com.github.MilkBowl</groupId>
    <artifactId>VaultAPI</artifactId>
    <version>1.7</version>
</dependency>
````

**Comment by Sleaker** [comment]
please see @TheE response. I'll be updating the pom.xml and readme for where it can be linked to later for now use the jitpack release.
