### ISSUE TITLE
NPE in onDisable

### ISSUE THREAD

**Issue by Escyth** [MilkBowl/VaultAPI#72]
Hello there,

I have some data that I need to execute upon unloading the plugin to retrieve money to some specific players in a List, but when doing that I usually receive an NPE (NullPointerException) because the dependency is not found, the economy provider and vault unload before mine does.

Is there a fix to that issue? I thought about saving information to a YML file, but that could cause lag if a server had so many players.

If there's anything I need to provide, please inform me.

Any help would be appreciated,
Escyth

**Comment by Sleaker** [comment]
I don't think there's a deterministic way to handle unloads. This is not an issue with vault, but an issue with MC plugin/server interaction. I have never tried doing anything in unload so I can't really help you here.
