### ISSUE TITLE
Group weight

### ISSUE THREAD

**Issue by DeepRobin** [MilkBowl/VaultAPI#73]
Please add a getWeight or getLadder Method for Permissions. (for developer, who like to sort something from for ex. admin to member)

**Comment by Sleaker** [comment]
This is what primary groups are for.  weighting has been too feature dependant to add it into an API. If you need to support a permission system explicitly for that feature it's generally better to link directly to the permission system you're wanting to support only.  Alternatively request from the permission implementation that getGroups() returns a pre-sorted array.
