### ISSUE TITLE
Chat Setup Returns Null

### ISSUE THREAD

**Issue by grandmen123** [MilkBowl/VaultAPI#74]
Issue: Chat Setup returns Null

Log: https://pastebin.com/HNFR4qew
Main.java: https://pastebin.com/Kx0UCzCP

When I load up the world and setup chat/permissions/economy I get Perms and Economy setup but chat seems to return null (You can see by the output statement "log.info("Is chat working " + this.setupChat() + "");" line 32.

I'm using the most up to date vault, any idea on why this is happening?

Thanks in advance!

**Comment by Sleaker** [comment]
You don't have a plugin that provides chat info support.

**Comment by entonoire** [comment]
hey! i'm having the same issue and i'm searching everywhere (luckperms github, skript github, ...) and i don't found an other way to register the chat service, when you say that "You don't have a plugin that provides chat" you don't say how you can get one or better, create one
