### ISSUE TITLE
Missing Vault dependency, with vault plugin installed

### ISSUE THREAD

**Issue by TheGreyDiamond** [MilkBowl/VaultAPI#75]
My Plugin can't find Vault, but I installed Vault on my server. I'am using your start example.

**Comment by Sleaker** [comment]
Please check your logs and/or post them in a gist. Most likely you're trying to access an economy, but you don't have an economy installed. Vault doesn't come with an economy, you'll need to install and setup an economy plugin if you're trying to interact with an economy.
