### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by erland-yt** [MilkBowl/VaultAPI#76]
how do I add money to myself? need I addon to do that?

**Comment by erland-yt** [comment]
what do I need to do to add money ingame?

**Comment by woutwoot** [comment]
Friendly tip: spend more time explaining what you're doing or expect the issue to be closed again :)

If you're taking about the actual API see the example on the main page.
`EconomyResponse r = econ.depositPlayer(player, 1.05);`

If you're talking about in a game, this is not the place to ask as it is specific to your economy plugin.

**Comment by Sleaker** [comment]
@erland-yt as @woutwoot explained, this has nothing to do with interacting with Vault. Go look up the commands for the economy you're using on your server on how to add money. If you're trying to add money through the API go read through the Economy.java class to see what functions are available.
