### ISSUE TITLE
VaultAPI Dependency Evaluation 

### ISSUE THREAD

**Issue by klugemonkey** [MilkBowl/VaultAPI#77]
If a Test plugin is created to depend on the VaultAPI, given the examples, one would implement the checking for Vault in the onEnable() and disable if not available. 
Similarly, if using the Economy, Chat or Permissions features of the API, according to the example, one also checks in the onEnable() and disables those features accordingly.  This plugin depends on Vault, so it will load after Vault in the plugin manager.  So far, so good.  

But lets say we have an Economy provider plugin, it too, depends on the VaultAPI and exposes the methods for the Economy.  This plugin loads and since it's dependent on Vault loads after the Vault plugin.  One would think that somehow this Economy provider would always be loaded before the Test plugin that is consuming the Economy services.  However, this is not always the case.  

There seems to be no correlation between the two dependencies and in certain cases of ordering, the Test plugin will sometimes load before the Economy provider plugin and thus fail to find the Economy and disable itself, according to the examples provided.

The question is whether it is documented somewhere that an Economy provider plugin depending on VaultAPI should be setup to load on STARTUP, or whether the examples provided for Test plugin, should be changed to delay the checking of Economy, Chat and Permissions providers until after all plugins load with a delayed synchronous task runnable.

**Comment by Sleaker** [comment]
I don't provide examples for a provider plugin, when people ask I mention that they should be setup to load on startup.

**Comment by Sleaker** [comment]
This issue is not applicable to VaultAPI to begin with as it's not a bukkit plugin and can't be loaded by a minecraft server.
