### ISSUE TITLE
[Feature] NukkitX support

### ISSUE THREAD

**Issue by GMatrixGames** [MilkBowl/VaultAPI#78]
Hello,

I'm currently suggesting a port of VaultAPI & the Vault plugin for the Bedrock Server Software NukkitX.

I would be willing to fulfill this port, with a PR to both of the repositories, but I would like to ask an opinion on weather it would be accepted or not before I put the time in to making it.

**Comment by Sleaker** [comment]
Not sure what you mean. Vault is an API layer. Program your plugin to use it's interfaces.
