### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ElectroGamesYT** [MilkBowl/VaultAPI#84]
I need help, I get this error with alot of my plugins.
`[18:24:47 ERROR]: [Shop] Disabled due to no Vault dependency found. (Example: Essentials)`
`[18:24:47 ERROR]: [HeadHunter] Could not connect to Vault. Make sure Vault is installed for HeadHunter!`
And alot more. My Minecraft version is 1.12 and ive tried all of the Vault versions. All of the versions worked but the plugins cant find them. Please help.

**Comment by Sleaker** [comment]
https://www.curseforge.com/minecraft/bukkit-plugins/vault/files - please install a version that is tagged to work with 1.12

**Comment by ElectroGamesYT** [comment]
None of them are tagged to work with 1.12

**Comment by Sleaker** [comment]
1.5.6 should work fine.
