### ISSUE TITLE
Help with playerInGroup / getPrimaryGroup

### ISSUE THREAD

**Issue by some0ne3** [MilkBowl/VaultAPI#87]
Hello, I need to check if player is in group, how would I do that?
I tried 
`Permission perm = null;
if(perm.playerInGroup(p,group)){
}
` but it doesn't work. Any ideas? :)

**Comment by woutwoot** [comment]
Did you properly set up Vault? See the information on the GitHub readme. (especially `setupPermissions()`)

**Comment by some0ne3** [comment]
yes, I put setupPermissions () in onEnable, my plugin returns an error when the code is executed (line from `if (perm.playerInGroup (p, group)) {}` Am I writing it correctly?> `Permission perm = null;`

**Comment by Sleaker** [comment]
unfortunately I don't have the time to help debugging developing against the API on here, I would suggest reaching out to spigot/bukkit communities for help in plugin development
