### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by darkt1981** [MilkBowl/VaultAPI#91]
[22:23:17] [Craft Scheduler Thread - 2/INFO]: [Vault] Checking for Updates ...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.comphenix.net.sf.cglib.core.ReflectUtils$1 (file:/home/container/plugins/ProtocolLib.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.comphenix.net.sf.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

error on server startup Spigot 1.15.2

**Comment by Sleaker** [comment]
ProtocolLib is not in vault. You have another plugin that's doing something bad when an http connection is being made.
