### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by byRaqe** [MilkBowl/VaultAPI#92]
When I use the method of set upping the Economy, my plugin returns false and says Vault is not on the Server while it is on the Server.

**Comment by Sleaker** [comment]
Make sure you have Vault and an Economy plugin installed. It's most likely telling you that you don't have an Economy plugin installed.  Without any form of logs or code I can't help.

**Comment by byRaqe** [comment]
https://hasteb.in/ufolilum.java

Here is my Class, but i would like to write my own Economy, so must I have an Economy Plugin?

**Comment by Sleaker** [comment]
Vault is not an economy plugin, it provides a layer for economy plugins to be used over a standard interface.  If you want to build a plugin that requires an economy you use something like the class you linked. If you want to build an economy plugin, then you implement the economy interface and register the service in the bukkit services manager.

Creating an economy and using an economy are two very different things.
