### ISSUE TITLE
Vault API Error

### ISSUE THREAD

**Issue by PookEveryDayBro** [MilkBowl/VaultAPI#93]
> [04:21:24 ERROR]: Error occurred while enabling testv1.0 (Is it up to date?)
java.lang.NullPointerException
at me.elior.test.Main.setupChat(Main.java:69) ~[?:?]
at me.elior.test.Main.onEnable(Main.java:57) ~[?:?]

line 69 : chat = rsp.getProvider();
line 57 : setupChat();

**Comment by Sleaker** [comment]
well, if getProvider() is giving you an NPE then that means rsp is null. I can't really help beyond that as you didn't really post source.
