### ISSUE TITLE
Allow prefixes and suffixes to be defined by a text component

### ISSUE THREAD

**Issue by lucyy-mc** [MilkBowl/VaultAPI#94]
It appears that Mojang have abandoned "legacy" text formatting using formatter codes, instead focussing on JSON text components. A key example of this is the addition of RGB text. Allowing plugins to set a text component as a prefix or a suffix instead of a string encoded with formatter codes would allow these new features to be used. 

Vault is a key player here - text components have failed to be widely used, with many systems still utilising formatter codes. Implementing the component system would encourage plugin developers to update their plugins to use the new format.

**Comment by Sleaker** [comment]
I'm not sure specifically how this affects Vault, a plugin can use a text component as a prefix regardless. That's more or less up to the chat system.

**Comment by lucyy-mc** [comment]
That's true, and text components are JSON anyway so they could fit nicely into a string. I'll close this issue now.
