### ISSUE TITLE
Issue with Vault throwing an error in TAB while using GroupManager

### ISSUE THREAD

**Issue by strahil211** [MilkBowl/VaultAPI#98]
Paper 1.16.3 #198

Plugin version ("latest" is not a version)
Vault 1.7.3
TAB 2.8.7
GM v2.8

Describe the bug
After updating to TAB 2.8.7 from 2.8.6, an error appeared and does not seem fixable.

How to reproduce
Install latest GroupManager v2.8, TAB 2.8.7, and Vault 1.7.3 error should appear.

Expected behavior
Did not have this error before updating TAB, but after contacting them about it they said its caused by Vault, so I'm posting it here. Expected behavior is to not have an error!

Actual behavior
Guaranteed error on every launch.

Additional info (errors, screenshots, ...)
All plugins are functioning and up to date, everything works as intended. However here is the error involving Vault:

17.09.2020 - 14:29:00 - [TAB v2.8.7] An error occurred when refreshing placeholders
17.09.2020 - 14:29:00 - java.lang.NullPointerException: null
17.09.2020 - 14:29:00 - at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.getWorldPermissions(WorldsHolder.java:548)
17.09.2020 - 14:29:00 - at net.milkbowl.vault.chat.plugins.Chat_GroupManager.getPlayerPrefix(Chat_GroupManager.java:272)
17.09.2020 - 14:29:00 - at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:67)
17.09.2020 - 14:29:00 - at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:91)
17.09.2020 - 14:29:00 - at me.neznamy.tab.platforms.bukkit.placeholders.BukkitPlaceholderRegistry$10.get(BukkitPlaceholderRegistry.java:146)
17.09.2020 - 14:29:00 - at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:20)
17.09.2020 - 14:29:00 - at me.neznamy.tab.shared.features.PlaceholderManager$1.run(PlaceholderManager.java:83)
17.09.2020 - 14:29:00 - at me.neznamy.tab.shared.cpu.CPUManager$4.run(CPUManager.java:119)
17.09.2020 - 14:29:00 - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
17.09.2020 - 14:29:00 - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
17.09.2020 - 14:29:00 - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
17.09.2020 - 14:29:00 - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
17.09.2020 - 14:29:00 - at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by strahil211** [comment]
This error disappeared. Not sure what fixed it.

**Comment by Sleaker** [comment]
@strahil211 this doesn't look related to Vault, but more related to potential issue with concurrency problems in some libraries tries to provide or access player information.
