### ISSUE TITLE
How to hook own Economy into Vaukt

### ISSUE THREAD

**Issue by PrimeAPI** [MilkBowl/VaultAPI#99]
Hey, is it possibly to hook my own Economy into Vault, so all other Plugins, who use the Vault API to get and set values, would chance the amount of money in my Plugin?

~ Lukas S, | PrimeAPI

**Comment by kayak503** [comment]
I believe you can still hook into Vault using a similar technique to this man [https://www.youtube.com/watch?v=3TTAe0xOdBM&ab_channel=%7BTheSourceCode%7D](url)

**Comment by Sleaker** [comment]
@PrimeAPI the video that kayak503 linked explains how to create an economy implementation and towards the 8m mark starts to go over how to create the hook so that it gets enabled on load.
